name: thoughts_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logger: ^2.2.0
  go_router: ^13.2.1
  json_theme: ^6.4.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
flutter:
  uses-material-design: true
  assets:
    - assets/theme/