name: thoughts_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logger: ^2.2.0
  go_router: ^14.0.1
  json_theme: ^6.4.1+2
  freezed: ^2.5.2
  build_runner: ^2.4.9
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  just_audio: ^0.9.37
  audio_session: ^0.1.19
  rxdart: ^0.27.7
  dio: ^5.4.3+1
  flutter_secure_storage: ^4.2.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
flutter:
  uses-material-design: true
  assets:
    - assets/theme/
    - assets/json/
    - assets/image/
    - assets/mp3/