name: 'Thoughts App CI/CD
'
on:
 push:
   branches:
     - master
     - main
jobs:
  analyze-flutter-project:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze .
      - run: dart format --set-exit-if-changed .

  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [analyze-flutter-project]
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test

  build-android-release:
    needs: run-tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter build apk --dart-define=base-url=${{secrets.BASE_URL}} --release
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          token: ${{secrets.TOKEN}}
          tag: v1.0.${{github.run_number}}
          generateReleaseNotes: true